<a href="https://colab.research.google.com/github/gaya3-b/LEARN.PY/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [ ]:
#please provide your answer below this line.
import numpy as np
x=np.random.random((3,3))
print(x)

[[0.63697826 0.71390099 0.4346076 ]
 [0.59171118 0.54907432 0.70686861]
 [0.98878064 0.63628499 0.83082995]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [1]:
#please provide your answer below this line.
import numpy as np
x=np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12),(13,14,15,16)])
y=np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12),(13,14,15,16)])
print(x)
print(y)
#reshape to 2*8 matrix
a=x.reshape(2,8)
b=y.reshape(2,8)
print(a)
print(b)
#horizontal stack
np.hstack((a,b))
#vertical stack
c=np.vstack((a,b))
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
