<a href="https://colab.research.google.com/github/gaya3-b/LEARN.PY/blob/main/TASK_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a DataFrame by passing a random numpy array,with a datetie index and labelled columns.and display its,
     - Head
     - Tail
     - Index 
     - Columns
     - Values
     - statistics


In [1]:
#please type your answer below this line.
import numpy as np
import pandas as pd
datetie = pd.date_range('2021-08-24',periods=4)
df = pd.DataFrame(np.random.randn(4,4), index=datetie, columns=list('ABCD'))
print("Head:\n", df.head())
print("Tail:\n", df.tail())
print("Index:\n", df.index)
print("Columns:\n", df.columns)
print("Values:\n", df.values)
print("Statistics:\n", df.describe(include='all'))

Head:
                    A         B         C         D
2021-08-24  0.949050  1.289264 -0.830205  0.084887
2021-08-25  0.329984 -0.163477 -0.825139 -0.008752
2021-08-26  0.943232 -1.259288  0.385874  0.189778
2021-08-27  0.423634 -1.081256 -1.222128  0.066735
Tail:
                    A         B         C         D
2021-08-24  0.949050  1.289264 -0.830205  0.084887
2021-08-25  0.329984 -0.163477 -0.825139 -0.008752
2021-08-26  0.943232 -1.259288  0.385874  0.189778
2021-08-27  0.423634 -1.081256 -1.222128  0.066735
Index:
 DatetimeIndex(['2021-08-24', '2021-08-25', '2021-08-26', '2021-08-27'], dtype='datetime64[ns]', freq='D')
Columns:
 Index(['A', 'B', 'C', 'D'], dtype='object')
Values:
 [[ 0.94904972  1.28926354 -0.83020455  0.08488654]
 [ 0.32998358 -0.16347657 -0.82513872 -0.00875249]
 [ 0.94323234 -1.25928781  0.3858738   0.18977757]
 [ 0.42363423 -1.08125588 -1.22212767  0.06673519]]
Statistics:
               A         B         C         D
count  4.000000  4.000000  4.000000

2. Use the above table and,
      - find transpose of your data.
      - sort the index in the descending order of the date.

In [2]:
#please provide your answer below this line.
print("Transpose\n", df.transpose())
print("Sorted in Descending Order\n", df.sort_index(ascending=False))

Transpose
    2021-08-24  2021-08-25  2021-08-26  2021-08-27
A    0.949050    0.329984    0.943232    0.423634
B    1.289264   -0.163477   -1.259288   -1.081256
C   -0.830205   -0.825139    0.385874   -1.222128
D    0.084887   -0.008752    0.189778    0.066735
Sorted in Descending Order
                    A         B         C         D
2021-08-27  0.423634 -1.081256 -1.222128  0.066735
2021-08-26  0.943232 -1.259288  0.385874  0.189778
2021-08-25  0.329984 -0.163477 -0.825139 -0.008752
2021-08-24  0.949050  1.289264 -0.830205  0.084887
