<a href="https://colab.research.google.com/github/gaya3-b/LEARN.PY/blob/main/TASK_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create two arrays, one containing elements [1,2], [3,4] and another containing elements [8,18] Now find the solution for this linear equation.

In [2]:
#please type your answer below this line.
import numpy as np
a=np.array([(1,2),(3,4)])
b=np.array((8,18))
print(np.linalg.solve(a,b))

[2. 3.]


2. Create an array containing elements [2, 3, 4]. Now find the sin,cos,tan values of this array elements.

In [3]:
#please type your answer below this line.
import numpy as np
a=np.array((2,3,4))
print(np.sin(a*np.pi/180))
print(np.cos(a*np.pi/180))
print(np.tan(a*np.pi/180))

[0.0348995  0.05233596 0.06975647]
[0.99939083 0.99862953 0.99756405]
[0.03492077 0.05240778 0.06992681]


3. Given b=[5,6], then find,

  a) 2sinb
  b) 2cos3b
  c) 4tan2b

In [4]:
#please type your answer below this line.
import numpy as np
b=np.array((5,6))
print(2*np.sin(b*np.pi/180))
print(2*np.cos(3*b*np.pi/180))
print(4*np.tan(2*b*np.pi/180))

[0.17431149 0.20905693]
[1.93185165 1.90211303]
[0.70530792 0.85022625]
